### ISSUE TITLE
Ticketkauf

### ISSUE THREAD

**Issue by XxPhenixX** [Sturmflut/ubuntu-touch-bdnavigator#1]
Hey!
Wenn man den UserAgent auf den von Windows Phone bezieht, kann man Tickets kaufen und man bekommt das Ticket per E-Mail und MMS zugesendet.
Ansonsten sehr schöne WebApp :)
Grüße

**Comment by Sturmflut** [comment]
Thanks for reporting this. Could you please tell me which user agent string you used exactly? I've tried some, but in no case do I get an option to buy a ticket. They only button I get is "Reservierung" (Reservation).

(Wie lautete denn der verwendete User Agent genau? Bei all meinen Versuchen bekam ich höchstens einen Link für "Reservierung", konnte aber nie ein Ticket kaufen.)

**Comment by XxPhenixX** [comment]
Since yesterday, the Deutsch Bahn stopped there MMS Service, but you still get an OnlineTicket via E-Mail.

userAgent: "Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 920);DBNavigator/15060000/Android REL 19/X"

and i also added a Login Button:

webView.url = "https://fahrkarten.bahn.de/mobile/st/st.post?lang=de" 

Because since yesterday, it also looks as you can only buy a ticket if you have logged in before otherwise you can only book a reservation.

**Comment by Sturmflut** [comment]
I no longer maintain the app and no longer own any Ubuntu Touch devices, sorry.
